export const FILE_SOURCE_TYPE_UPLOAD = 'UPLOAD'; // 上传
export const FILE_SOURCE_TYPE_CRAWLER = 'CRAWLER'; // 爬虫

export enum ENUM_FILE_SOURCE_TYPES {
  UPLOAD = FILE_SOURCE_TYPE_UPLOAD,
  CRAWLER = FILE_SOURCE_TYPE_CRAWLER,
}
