version: '3.1'
services:
  kb-server:
      build: './'
      user: 'myuser'
      ports:
        - '3001:3000'
      volumes:
        - '/etc/localtime:/etc/localtime:ro'
        - './.env:/home/myuser/.env:ro'
        - './resources/prod:/home/myuser/resources/prod:rw'
        - '../knowledge-base-admin/dist:/home/myuser/client'

